### ISSUE TITLE
Parsing a scenario as part of a feature/rule, results in a scenario outline instance.

### ISSUE THREAD

**Issue by gula123** [gherking/gherkin-ast#19]
**Preconditions**:
Have a feature file that contains a feature or a rule containing at least one scenario:
e.g.:
//test.feature
```
Feature: Hello world

    Scenario: Name of scenario
    Description of the scenario

      Given this is a given step
```

**Steps to reproduce**:

1. Parse and log the feature file from the preconditions with gherkin-io's read function
```
import { read } from "gherkin-io";
console.log(read(test.feature));
```
2. Observe the returned objects type

**Actual results**:
2. Scenario is parsed as a scenario outline
```
Document {
        uri: 'tests/testData/issuetest.feature',
        feature: Feature {
          keyword: 'Feature',
          name: 'Hello world',
          description: '',
          language: 'en',
          elements: [ [ScenarioOutline] ],
          tags: []
        }
      }
```

**Expected results**:
2. Scenario is parsed as a scenario

*Note*: Issue is registered in gherkin-ast as gherkin-io's read function is using parse functions of gherkin-ast

**Comment by szikszail** [comment]
Fix is released. v3.0.2
