### ISSUE TITLE
[Q] Allowing empty table cells

### ISSUE THREAD

**Issue by fthouraud** [gherking/gherkin-ast#29]
Hello 👋 

## Summary/Question

While looking for a solution to format our feature files, I've found your library ([gherkin-formatter](https://github.com/gherking/gherkin-formatter) in fact).

This looks really great but it doesn't allow empty table cells.

Is this something you wanted or would it be possible to accept empty values on a table cell? I'll be glad to help if needed.

### Details

We're using [Veggies](https://github.com/ekino/veggies) to validate our JSON output and we sometimes use the `defined` matcher which does not expect a value to match.

```gherkin
Scenario: Posting a new entity should return all posted fields plus an id
  Given I set request body
    | key  | value           |
    | text | Just an example |
  When I POST /api/v1/message
  Then response status code should be 200
  And json response should match
    | field | matcher | value           |
    | id    | defined |                 |
    | text  | equals  | Just an example |
```

## Impact/Urgency

It is not really urgent. We're just looking for a way to format our feature files.

Regards

**Comment by szikszail** [comment]
@fthouraud thank you for reaching out!
I agree gherking should support this case.
Could you please share what error you get or what is the behavior in your case? It would help us :)

**Comment by szikszail** [comment]
Ah, here is the issue: https://github.com/gherking/gherkin-ast/blob/master/src/ast/tableCell.ts#L9
We will handle it as a bug and fix it.

**Comment by fthouraud** [comment]
That's great! Thank you @szikszail 🙏

**Comment by szikszail** [comment]
@fthouraud I released gherkin-ast@3.0.3, could you please confirm that it fixed your issue?

**Comment by fthouraud** [comment]
Sorry @szikszail, I've been out of time lately. Thank you for this, I'll try to test it next week and I'll keep you informed! 🙏

**Comment by fthouraud** [comment]
This works perfectly. Thanks @szikszail 🙏

**Comment by szikszail** [comment]
@fthouraud thank you for checking!
